service: openfaas-hello-world

provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  hello-world:
    lang: node
    handler: ./hello-world
    image: hello-world:0.1

plugins:
  - serverless-openfaas

package:
  artifact: none
